version: '3'

services:
  app:
    image: y4tu/logsapp
    container_name: logsapp
    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - app