version: '3'

services:
  app:
    image: node
    build: .
    container_name: logsapp
    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:8080
      - 443:4430
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./keys/3.23.193.203.crt:/etc/nginx/3.23.193.203.crt
      - ./keys/3.23.193.203.key:/etc/nginx/3.23.193.203.key
      - ./sites-available/example.com:/etc/nginx/sites-available/example.com
      - ./sites-enabled/example.com:/etc/nginx/sites-enabled/example.com
    command: rm ./sites-enabled/default
    restart: always
    links:
      - app