version: '3'

services:
  app:
    image: node
    build: .
    container_name: logsapp
    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:8080
      - 443:4430
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./keys/manjaro_work.crt:/etc/nginx/manjaro_work.crt
      - ./keys/manjaro_work.key:/etc/nginx/manjaro_work.key
    restart: always
    links:
      - app